#!/bin/sh
#
# When we wakeup from suspend, both devices are turned on.  This causes
# unexpected power draw and confuses switcheroo.  Turn the unused device
# back on before suspend and off after resume so everyone is in sync.

case "$1" in
	suspend|hibernate)
	if [ -e /sys/kernel/debug/vgaswitcheroo/switch ]; then
		echo ON > /sys/kernel/debug/vgaswitcheroo/switch
	fi
	/sbin/setpci -s 2.0 F4.B > /tmp/.lid.level
	exit 0
	;;
	resume|thaw)
	if [ -e /sys/kernel/debug/vgaswitcheroo/switch ]; then
		echo OFF > /sys/kernel/debug/vgaswitcheroo/switch
	fi
	if [ -e /tmp/.lid.level ]; then
		/sbin/setpci -s 2.0 F4.B=$(cat /tmp/.lid.level)
	fi
	exit 0
	;;
	*)
	echo "Usage $0 {suspend|hibernate|resume|thaw}"
	exit 1
esac
