#!/bin/sh

case "$1" in
	suspend|hibernate)
	/sbin/setpci -s 2.0 F4.B > /tmp/.ul30vt.brightness
	exit 0
	;;
	resume|thaw)
	if [ -e /tmp/.ul30vt.brightness ]; then
		/sbin/setpci -s 2.0 F4.B=$(cat /tmp/.ul30vt.brightness)
	fi
	exit 0
	;;
	*)
	echo "Usage $0 {suspend|hibernate|resume|thaw}"
	exit 1
esac
